TASK-2250 코답 OF (codap)
team-monolith-product/codap pull request #3
Opened 2024-12-10 07:33 UTC by paulkim3151

2024-12-16 08:09 UTC, a3626a requested changes

2024-12-16 08:09 UTC, a3626a commented on apps/dg/main.js
> +    ].concat(viewModeMenu);
요것이 낫지 않나요?
```suggestion
    var editModeMenu = [
      { name: "DG.fileMenu.menuItem.openDocument".loc(), action: "openFileDialog" },
    ] + viewModeMenu;
```

2024-12-16 08:09 UTC, a3626a commented on apps/dg/main.js
> +    var observeModeMenu = [{ name: "내보내기", action: "exportFile" }];
이건 혹시 기본 localizedname이 먼가요? action은 있는데 localized name이 없낭뇨?

2024-12-17 01:03 UTC, paulkim3151 commented on apps/dg/main.js
> +    var observeModeMenu = [{ name: "내보내기", action: "exportFile" }];
exportFile도 저희가 만든 custom action입니다. 
(CFM에 함수를 만들었습니다. 제가 CFM 1차 리뷰때 설명을 못 드렸던 것 같네요...)
https://github.com/team-monolith-product/cloud-file-manager/pull/1/files#diff-c17f33ed5015b68b23af050b4be9bdca79e80e74731d70c19ebc7236a92bb396R1118-R1132

2024-12-17 01:05 UTC, paulkim3151 commented on apps/dg/main.js
> +    ].concat(viewModeMenu);
javascript에서 두 배열의 `+` 연산 값은 string이 되네요.

![image](https://github.com/user-attachments/assets/ee68efa9-3457-42ad-ab1a-e5fd0290fcbc)

2024-12-17 01:06 UTC, a3626a commented on apps/dg/main.js
> +    ].concat(viewModeMenu);
이게 언제부터 이랬지

2024-12-17 01:07 UTC, a3626a commented on apps/dg/main.js
> +    ].concat(viewModeMenu);
원래 안됐네 ㄷㄷ

2024-12-17 01:07 UTC, a3626a approved these changes

2024-12-17 08:05 UTC, merged